from ...board import BOARD_COLUMNS, BOARD_ROWS

# Feature Planes:
FP_OUR_FLAG = 0
FP_OUR_TOWER = 1
FP_OUR_RANK_1 = 2
FP_OUR_RANK_2 = 3
FP_OUR_RANK_3 = 4
FP_OUR_RANK_4 = 5
FP_OUR_RANK_5 = 6
FP_OUR_RANK_6 = 7
FP_THEIR_FLAG = 8
FP_THEIR_TOWER = 9 
FP_THEIR_RANK_1 = 10
FP_THEIR_RANK_2 = 11
FP_THEIR_RANK_3 = 12
FP_THEIR_RANK_4 = 13
FP_THEIR_RANK_5 = 14
FP_THEIR_RANK_6 = 15
FP_PASSABLE = 16
FP_INACTIVITY_COUNT = 17
# Engineered Planes
FP_OUR_FLAG_REL_X = 18
FP_OUR_FLAG_REL_Y = 19
FP_THEIR_FLAG_REL_X = 20
FP_THEIR_FLAG_REL_Y = 21
FP_OUR_RANK_1_QUANTITY = 22
FP_OUR_RANK_2_QUANTITY = 23
FP_OUR_RANK_3_QUANTITY = 24
FP_OUR_RANK_4_QUANTITY = 25
FP_OUR_RANK_5_QUANTITY = 26
FP_OUR_RANK_6_QUANTITY = 27
FP_THEIR_RANK_1_QUANTITY = 28
FP_THEIR_RANK_2_QUANTITY = 29
FP_THEIR_RANK_3_QUANTITY = 30
FP_THEIR_RANK_4_QUANTITY = 31
FP_THEIR_RANK_5_QUANTITY = 32
FP_THEIR_RANK_6_QUANTITY = 33

TOTAL_FP_COUNT = 34

MOVEMENT_INDEX = {
    #(row_delta, column_delta)
    (1, 0): 0,
    (0, 1): 1,
    (-1, 0): 2,
    (0, -1): 3,
    (2, 0): 4,
    (0, 2): 5,
    (-2, 0): 6,
    (0, -2): 7,
}

MOVEMENTS_PER_POSITION = len(MOVEMENT_INDEX)
ACTION_SPACE_SHAPE = (MOVEMENTS_PER_POSITION, BOARD_ROWS, BOARD_COLUMNS)
INPUT_SHAPE = (TOTAL_FP_COUNT, BOARD_ROWS, BOARD_COLUMNS)

